name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge
        activate-environment: bigman
    - run: |
        conda init bash
        conda activate bigman
        conda install pytest
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        ls /usr/share/miniconda/envs/bigman/bin
        pytest
